#include <iostream>

using namespace std;

int main()
{
    cout << "                               .=+:               " << endl;
    sleep(100);
    cout << "                             -*@@@%               " << endl;
    sleep(100);
    cout << "                          :*@@@@%*.               " << endl;
    sleep(100);
    cout << "                       .+@@@@%*:                  " << endl;
    sleep(100);
    cout << "                   ..=%@@@%*-                     " << endl;
    sleep(100);
    cout << "                .=%#*%@@%-                        " << endl;
    sleep(100);
    cout << "              -#@##@#**.    :+**=.                " << endl;
    sleep(100);
    cout << "           :-=@@@@%%@#+    *@#+++*+               " << endl;
    sleep(100);
    cout << "           ###@@@@#==+=:. .%@#*+==#.              " << endl;
    sleep(100);
    cout << "            +@@@*   =*#+- =@%##===:               " << endl;
    sleep(100);
    cout << "            .@@=.     .%+=.#@#+==-                " << endl;
    sleep(100);
    cout << "            :@#        :#*++###+=-.               " << endl;
    sleep(100);
    cout << "            *@#:::.::--+@@%*+==*+---:             " << endl;
    sleep(100);
    cout << "            *%##%*#%@@@%@%%@#+--%:---.            " << endl;
    sleep(100);
    cout << "            .**#%%%@@@@@##@@@@#%%+++-             " << endl;
    sleep(100);
    cout << "                ::. .%@@@@@@@@@%#+--:             " << endl;
    sleep(100);
    cout << "                    :@@@@@@@#*+==++*:             " << endl;
    sleep(100);
    cout << "                    *@@@@@%%*--=-=+=              " << endl;
    sleep(100);
    cout << "                   *@@@@@%%#%=--:--.              " << endl;
    sleep(100);
    cout << "                  -@@@@@%####*----=               " << endl;
    sleep(100);
    cout << "                 .@@@@@@%###***+*+:               " << endl;
    sleep(100);
    cout << "                :@@@@@@@@%##*+*++                 " << endl;
    sleep(100);
    cout << "               -@@@@@@@@@%%##**##.                " << endl;
    sleep(100);
    cout << "              =@@@@@@@@@%%%##****-                " << endl;
    sleep(100);
    cout << "             =@@@@@@@@@@%%%####**+                " << endl;
    sleep(100);
    cout << "            -@@@@@@@@@@@%%###%%***                " << endl;
    sleep(100);
    cout << "            %@@@@@@@@@@%%####@@#**                " << endl;
    sleep(100);
    cout << "            .+@@@@@@@@%%####%@@%*#.               " << endl;
    sleep(100);
    cout << "              .#@@@@@%%####-:@@@%#+               " << endl;
    sleep(100);
    cout << "               #@@@@@%###*=  +@@@%#=              " << endl;
    sleep(100);
    cout << "               *@@@@+ .:-=   :@@@@%#              " << endl;
    sleep(100);
    cout << "              .%@@@@=         =@@@%%.             " << endl;
    sleep(100);
    cout << "              .%@@@+           #@@@%=             " << endl;
    sleep(100);
    cout << "            .+@@@@*            -@@@%#             " << endl;
    sleep(100);
    cout << "          :#@@@%==             .%@@@#             " << endl;
    sleep(100);
    cout << "           ::..                 .@@%*             " << endl;
    sleep(100);
    cout << "                                .@@%#             " << endl;
    sleep(100);
    cout << "                                *@@@%             " << endl;
    sleep(100);

    return 0;
}
